# Generated by Django 4.1.2 on 2023-07-06 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id_comuna',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id_region',
        ),
    ]
