# Generated by Django 4.1.2 on 2023-07-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0004_productocarrito_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productocarrito',
            name='estado',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
