# Generated by Django 4.1.2 on 2023-06-27 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carrito', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoEnvio',
            fields=[
                ('id_est_envio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado_env', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id_ubicacion', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=200)),
                ('id_comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrito.comuna')),
                ('id_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrito.region')),
            ],
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id_envio', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_envio', models.DateField()),
                ('id_est_envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.estadoenvio')),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrito.pedido')),
                ('id_ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.ubicacion')),
            ],
        ),
    ]
