# Generated by Django 4.1.2 on 2023-07-06 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0002_envio_codigo_seguimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envio',
            name='id_ubicacion',
        ),
    ]
