# Generated by Django 4.1.2 on 2023-06-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicicletas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bicicleta',
            old_name='categoria',
            new_name='id_categoria',
        ),
        migrations.RenameField(
            model_name='bicicleta',
            old_name='marca',
            new_name='id_marca',
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='imagen',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
