# Generated by Django 4.1.2 on 2023-06-29 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicicletas', '0002_rename_categoria_bicicleta_id_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicicleta',
            name='imagen',
            field=models.ImageField(upload_to='productos/'),
        ),
    ]
