# Generated by Django 4.1.2 on 2023-06-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicicletas', '0004_alter_bicicleta_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicicleta',
            name='imagen',
            field=models.ImageField(upload_to=''),
        ),
    ]
